name: Deploy Infrastructure

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: Terraform Apply
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Navigate to Terraform directory
        run: cd terraform

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: apply -var-file=variables.json -auto-approve

      - name: Capture Terraform Outputs
        id: terraform_outputs
        run: |
          echo "::set-output name=bucket_name::$(terraform output -raw bucket_name)"

      - name: Terraform Show Outputs
        run: terraform output
